### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by Samuel12321** [michalleptuch/rounded-flyout#1]
APPX0501	Validation error. error 80080204: App manifest validation error: Line 198, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 42, Column 27.	RoundedFlyout.Package	C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Package\bin\x64\Debug	C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Package\bin\x64\Debug\AppxManifest.xml

**Comment by michalleptuch** [comment]
Fixed 😉

**Comment by michalleptuch** [comment]
Fixed 😉

**Comment by Samuel12321** [comment]
thanks

**Comment by Samuel12321** [comment]
Just tried it, error still persists.

**Comment by michalleptuch** [comment]
Did you try to clone repo again? What is a version of VS?

**Comment by michalleptuch** [comment]
> Just tried it, error still persists.

Did you try to clone repo again? What is a version of VS?

**Comment by Samuel12321** [comment]
yes, re-cloned repo
Vs Version 16.11.1

**Comment by michalleptuch** [comment]
I think it's problem with your VS. I use v16.9.8

**Comment by michalleptuch** [comment]
I checked it and other my Desktop Bridge apps again. It's an issue in Visual Studio >= 16.10.0. Even Visual Studio 2022 Preview can't build my projects. For example, Ink Workspace has the same issue:

`Validation error. error 80080204: App manifest validation error: Line 66, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 60, Column 27.	InkWorkspace.Package	D:\Repozytoria\InkWorkspace\InkWorkspace.Package\bin\x64\Debug\AppxManifest.xml`

I think someone smarter should take a look at this problem @marb2000...

**Comment by michalleptuch** [comment]
I checked it and other my Desktop Bridge apps again. It's an issue in Visual Studio >= 16.10.0. Even Visual Studio 2022 Preview can't build my projects. For example, Ink Workspace has the same issue:

`Validation error. error 80080204: App manifest validation error: Line 66, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 60, Column 27.	InkWorkspace.Package	D:\Repozytoria\InkWorkspace\InkWorkspace.Package\bin\x64\Debug\AppxManifest.xml`

I think someone smarter should take a look at this problem @marb2000.

**Comment by Samuel12321** [comment]
did you find a way around this?

**Comment by michalleptuch** [comment]
No update at this moment 😔

**Comment by michalleptuch** [comment]
@Samuel12321 check my recent changes: https://github.com/michalleptuch/rounded-flyout/tree/FixForNewerVS
It's only a draft and I don't know if it works in Release mode or when you publish MSIX package.
It may not work at the first run.

**Comment by Samuel12321** [comment]
Build and deploy work, but publish fails VS 2022 preview 5

> Found multiple publish output files with the same relative path: C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\obj\x86\Debug\CloseButtonControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x86\Debug\RoundedFlyout.Controls\CloseButtonControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\obj\x86\Debug\FlyoutContentControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x86\Debug\RoundedFlyout.Controls\FlyoutContentControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\obj\x86\Debug\FlyoutControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x86\Debug\RoundedFlyout.Controls\FlyoutControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\obj\x86\Debug\MainControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x86\Debug\RoundedFlyout.Controls\MainControl.xbf, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\obj\x86\Debug\RoundedFlyout.Controls.xr.xml, C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x86\Debug\RoundedFlyout.Controls\RoundedFlyout.Controls.xr.xml, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.3\runtimes\win10-x86\native\Microsoft.Toolkit.Win32.UI.XamlHost.pri, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\build\..\runtimes\win10-x86\native\Microsoft.Toolkit.Win32.UI.XamlHost.pri, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.3\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.winmd, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.winmd, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\build\..\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml, C:\Users\samue\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml.	RoundedFlyout.Package	C:\Program Files\dotnet\sdk\6.0.100-rtm.21511.39\Sdks\Microsoft.NET.Sdk\targets	C:\Program Files\dotnet\sdk\6.0.100-rtm.21511.39\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets	113	


plus there is a MSB3270 warning:

> Severity	Code	Description	Project	Path	File	Line	Suppression State
Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "C:\Users\samue\Source\Repos\rounded-flyout\RoundedFlyout.Controls\bin\x64\Debug\RoundedFlyout.Controls.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	RoundedFlyout.Wpf	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2304

**Comment by michalleptuch** [comment]
Okay, please check again. I added `<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>` to WPF project.
